// swift-tools-version: 6.0
// HankoSwift — Swift implementation of the Hanko v0.1 identity protocol.
//
// PROVENANCE: "Hanko" is the OBYW.one operator's own pre-existing internal
// codename, conceived independently. This package is gh:FJ-Studios/hanko-swift.
// Not related to teamhanko/hanko (a passkey project). See protocol/types.go.
//
// Companion to gh:FJ-Studios/hanko (Go reference implementation).
// All wire types mirror protocol/types.go v0.1 exactly.

import PackageDescription

let package = Package(
    name: "HankoSwift",
    platforms: [
        .macOS(.v14),
        .iOS(.v17),
    ],
    products: [
        // Wire types only — minimal, zero crypto dep.
        .library(name: "HankoCore",   targets: ["HankoCore"]),
        // Ed25519 sign/verify + RFC 8785 canonical JSON.
        .library(name: "HankoCrypto", targets: ["HankoCrypto"]),
        // Verifier orchestration: sig + revocation + scope + audience + replay.
        .library(name: "HankoBroker", targets: ["HankoBroker"]),
    ],
    targets: [
        .target(
            name: "HankoCore",
            dependencies: [],
            path: "Sources/HankoCore"
        ),
        .target(
            name: "HankoCrypto",
            dependencies: ["HankoCore"],
            path: "Sources/HankoCrypto"
        ),
        .target(
            name: "HankoBroker",
            dependencies: ["HankoCore", "HankoCrypto"],
            path: "Sources/HankoBroker"
        ),
        .testTarget(
            name: "HankoCoreTests",
            dependencies: ["HankoCore"],
            path: "Tests/HankoCoreTests"
        ),
        .testTarget(
            name: "HankoCryptoTests",
            dependencies: ["HankoCrypto"],
            path: "Tests/HankoCryptoTests",
            resources: [
                // Cross-language parity vectors generated by Go's gen_vectors_test.go.
                // Copy from ~/.shikki/tmp/wt-hanko-w5-*/docs/test-vectors/ when available.
                .process("Fixtures"),
            ]
        ),
        .testTarget(
            name: "HankoBrokerTests",
            dependencies: ["HankoBroker"],
            path: "Tests/HankoBrokerTests",
            resources: [
                .process("Fixtures"),
            ]
        ),
    ]
)
