// FixtureSupport.swift
// Shared fixture loading for the HankoCrypto parity tests.

import Foundation

/// One entry of `Fixtures/sign-verify.json` — generated by the Go repo's
/// `gen_vectors_test.go` (docs/test-vectors/).
struct SignVerifyVector: Decodable {
    let id: String
    let description: String
    let seedHex: String
    let publicKeyB64: String
    let canonicalBody: String
    let signatureB64: String

    enum CodingKeys: String, CodingKey {
        case id, description
        case seedHex = "seed_hex"
        case publicKeyB64 = "public_key_b64"
        case canonicalBody = "canonical_body"
        case signatureB64 = "signature_b64"
    }

    static func load() throws -> [SignVerifyVector] {
        guard let url = Bundle.module.url(forResource: "sign-verify", withExtension: "json") else {
            throw FixtureError.missing("sign-verify.json")
        }
        return try JSONDecoder().decode([SignVerifyVector].self, from: Data(contentsOf: url))
    }
}

/// One entry of `Fixtures/canonical-json.json`. `input` is arbitrary JSON,
/// so the fixture is parsed with JSONSerialization rather than Codable.
struct CanonicalVector {
    let id: String
    let input: Any
    let expected: String

    static func load() throws -> [CanonicalVector] {
        guard let url = Bundle.module.url(forResource: "canonical-json", withExtension: "json") else {
            throw FixtureError.missing("canonical-json.json")
        }
        let raw = try JSONSerialization.jsonObject(with: Data(contentsOf: url))
        guard let entries = raw as? [[String: Any]] else {
            throw FixtureError.malformed("canonical-json.json")
        }
        return try entries.map { e in
            guard let id = e["id"] as? String,
                  let input = e["input"],
                  let expected = e["expected_canonical"] as? String else
            {
                throw FixtureError.malformed("canonical-json.json entry")
            }
            return CanonicalVector(id: id, input: input, expected: expected)
        }
    }
}

enum FixtureError: Error {
    case missing(String)
    case malformed(String)
}

extension Data {
    /// Decode a lowercase/uppercase hex string ("0102ff…") into bytes.
    init?(hexString: String) {
        let chars = Array(hexString)
        guard chars.count % 2 == 0 else { return nil }
        var bytes: [UInt8] = []
        bytes.reserveCapacity(chars.count / 2)
        for i in stride(from: 0, to: chars.count, by: 2) {
            guard let byte = UInt8(String(chars[i...i + 1]), radix: 16) else { return nil }
            bytes.append(byte)
        }
        self.init(bytes)
    }
}
